import type { LoopResult } from "./types";

// AUTO-GENERATED by scripts/record.ts — a REAL captured WorldLine run (live Opus 4.8).
// Used as the instant, reliable demo default; "Re-run live" recomputes via /api/loop.
export const RECORDED = ({
  "base": {
    "id": "base",
    "records": [
      {
        "stepId": "intake",
        "name": "Intake",
        "kind": "llm",
        "output": {
          "claim": {
            "orderId": "A-4471",
            "customer": "Northwind Traders",
            "item": "Standard Widget (not final sale)",
            "amount": 240,
            "purchaseDate": "2026-05-28",
            "requestDate": "2026-06-10",
            "reason": "Arrived defective — the unit will not power on."
          },
          "daysSincePurchase": 13,
          "defectClaimed": true,
          "finalSale": false
        },
        "live": true,
        "usage": {
          "input": 477,
          "output": 20
        }
      },
      {
        "stepId": "fraud_check",
        "name": "Fraud Check",
        "kind": "llm",
        "output": {
          "fraudRisk": "LOW",
          "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and no signals of identity mismatch, repeat abuse, or impossible timeline are present."
        },
        "live": true,
        "usage": {
          "input": 568,
          "output": 80
        }
      },
      {
        "stepId": "classify",
        "name": "Classifier",
        "kind": "llm",
        "output": {
          "category": "OUT_OF_WINDOW"
        },
        "live": true,
        "usage": {
          "input": 732,
          "output": 20
        }
      },
      {
        "stepId": "retrieve_policy",
        "name": "Policy Retriever",
        "kind": "rule",
        "output": {
          "policyRule": {
            "eligible": false,
            "note": "Return window (30 days) has passed."
          }
        },
        "live": false
      },
      {
        "stepId": "eligibility",
        "name": "Eligibility",
        "kind": "rule",
        "output": {
          "eligible": false,
          "eligReason": "Return window (30 days) has passed."
        },
        "live": false
      },
      {
        "stepId": "amount",
        "name": "Amount",
        "kind": "rule",
        "output": {
          "amount": 0
        },
        "live": false
      },
      {
        "stepId": "decision",
        "name": "Decision",
        "kind": "llm",
        "output": {
          "decision": "DENY",
          "rationale": "Unfortunately, your refund request cannot be approved because it was submitted after the 30-day return window had passed."
        },
        "live": true,
        "usage": {
          "input": 418,
          "output": 52
        }
      }
    ],
    "finalState": {
      "claim": {
        "orderId": "A-4471",
        "customer": "Northwind Traders",
        "item": "Standard Widget (not final sale)",
        "amount": 240,
        "purchaseDate": "2026-05-28",
        "requestDate": "2026-06-10",
        "reason": "Arrived defective — the unit will not power on."
      },
      "daysSincePurchase": 13,
      "defectClaimed": true,
      "finalSale": false,
      "fraudRisk": "LOW",
      "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and no signals of identity mismatch, repeat abuse, or impossible timeline are present.",
      "category": "OUT_OF_WINDOW",
      "policyRule": {
        "eligible": false,
        "note": "Return window (30 days) has passed."
      },
      "eligible": false,
      "eligReason": "Return window (30 days) has passed.",
      "amount": 0,
      "decision": "DENY",
      "rationale": "Unfortunately, your refund request cannot be approved because it was submitted after the 30-day return window had passed."
    },
    "outcome": {
      "decision": "DENY",
      "amount": 0,
      "pass": false
    }
  },
  "bisect": {
    "evidence": [
      {
        "nodeId": "intake",
        "name": "Intake",
        "correct": true,
        "reason": "Days between 2026-05-28 and 2026-06-10 is 13, defect is claimed, item is not final sale. All extracted fields match the input claim and policy interpretation.",
        "intervened": false,
        "flipped": false
      },
      {
        "nodeId": "fraud_check",
        "name": "Fraud Check",
        "correct": true,
        "reason": "The fraud check correctly assesses LOW risk: timeline is consistent (13 days, requestDate after purchaseDate), defect claim is ordinary, item not final sale, and no abuse signals present. Output is consistent with input.",
        "intervened": false,
        "flipped": false
      },
      {
        "nodeId": "classify",
        "name": "Classifier",
        "correct": false,
        "reason": "Within 13 days (under 30-day window), defect claimed, not final sale — should be WITHIN_WINDOW_DEFECTIVE, not OUT_OF_WINDOW.",
        "correctOutput": {
          "category": "WITHIN_WINDOW_DEFECTIVE"
        },
        "intervened": true,
        "flipped": true
      },
      {
        "nodeId": "decision",
        "name": "Decision",
        "correct": true,
        "reason": "The decision step correctly applied its input: category was OUT_OF_WINDOW and eligible was false, so DENY with the matching rationale is the correct output given the input. The upstream categorization is wrong (13 days is within window, defective should be WITHIN_WINDOW_DEFECTIVE), but that is not this step's fault.",
        "intervened": false,
        "flipped": false
      }
    ],
    "culpritId": "classify",
    "culpritName": "Classifier",
    "forkRun": {
      "id": "bisect-classify",
      "records": [
        {
          "stepId": "intake",
          "name": "Intake",
          "kind": "llm",
          "output": {
            "claim": {
              "orderId": "A-4471",
              "customer": "Northwind Traders",
              "item": "Standard Widget (not final sale)",
              "amount": 240,
              "purchaseDate": "2026-05-28",
              "requestDate": "2026-06-10",
              "reason": "Arrived defective — the unit will not power on."
            },
            "daysSincePurchase": 13,
            "defectClaimed": true,
            "finalSale": false
          },
          "live": false,
          "usage": {
            "input": 477,
            "output": 20
          },
          "cached": true
        },
        {
          "stepId": "fraud_check",
          "name": "Fraud Check",
          "kind": "llm",
          "output": {
            "fraudRisk": "LOW",
            "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and no signals of identity mismatch, repeat abuse, or impossible timeline are present."
          },
          "live": false,
          "usage": {
            "input": 568,
            "output": 80
          },
          "cached": true
        },
        {
          "stepId": "classify",
          "name": "Classifier",
          "kind": "llm",
          "output": {
            "category": "WITHIN_WINDOW_DEFECTIVE"
          },
          "live": false,
          "forked": true
        },
        {
          "stepId": "retrieve_policy",
          "name": "Policy Retriever",
          "kind": "rule",
          "output": {
            "policyRule": {
              "eligible": true,
              "note": "Defective within the 30-day window — full refund."
            }
          },
          "live": false
        },
        {
          "stepId": "eligibility",
          "name": "Eligibility",
          "kind": "rule",
          "output": {
            "eligible": true,
            "eligReason": "Defective within the 30-day window — full refund."
          },
          "live": false
        },
        {
          "stepId": "amount",
          "name": "Amount",
          "kind": "rule",
          "output": {
            "amount": 240
          },
          "live": false
        },
        {
          "stepId": "decision",
          "name": "Decision",
          "kind": "llm",
          "output": {
            "decision": "APPROVE",
            "rationale": "Your refund of $240 has been approved because the item was found defective within the 30-day return window."
          },
          "live": true,
          "usage": {
            "input": 429,
            "output": 47
          }
        }
      ],
      "finalState": {
        "claim": {
          "orderId": "A-4471",
          "customer": "Northwind Traders",
          "item": "Standard Widget (not final sale)",
          "amount": 240,
          "purchaseDate": "2026-05-28",
          "requestDate": "2026-06-10",
          "reason": "Arrived defective — the unit will not power on."
        },
        "daysSincePurchase": 13,
        "defectClaimed": true,
        "finalSale": false,
        "fraudRisk": "LOW",
        "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and no signals of identity mismatch, repeat abuse, or impossible timeline are present.",
        "category": "WITHIN_WINDOW_DEFECTIVE",
        "policyRule": {
          "eligible": true,
          "note": "Defective within the 30-day window — full refund."
        },
        "eligible": true,
        "eligReason": "Defective within the 30-day window — full refund.",
        "amount": 240,
        "decision": "APPROVE",
        "rationale": "Your refund of $240 has been approved because the item was found defective within the 30-day return window."
      },
      "outcome": {
        "decision": "APPROVE",
        "amount": 240,
        "pass": true
      }
    }
  },
  "repair": {
    "nodeId": "classify",
    "nodeName": "Classifier",
    "originalPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- A return is valid ONLY if the request is made in the SAME CALENDAR MONTH as the purchase. If the request month differs from the purchase month, classify OUT_OF_WINDOW.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the reason is change-of-mind with no defect, classify BUYER_REMORSE.\n- Otherwise classify WITHIN_WINDOW_DEFECTIVE.",
    "patchedPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- The return window is 30 CALENDAR DAYS from the purchase date. A request is within the window if it is made on or before the 30th calendar day after the purchase date; calendar months are irrelevant. If the request is made more than 30 calendar days after the purchase date, classify OUT_OF_WINDOW.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the reason is change-of-mind with no defect (and the item is not final sale), classify BUYER_REMORSE.\n- If the item is defective on arrival, the request is within the 30-day window, and the item is not final sale, classify WITHIN_WINDOW_DEFECTIVE (full refund).\n- Otherwise classify WITHIN_WINDOW_DEFECTIVE.",
    "rootCause": "The prompt encoded an incorrect return-window rule. It instructed the classifier to treat a return as valid only within the SAME CALENDAR MONTH as purchase, and to mark anything in a different month as OUT_OF_WINDOW. The authoritative policy actually uses a rolling 30 CALENDAR DAYS from the purchase date. A claim made 13 days after purchase spanning a month boundary was therefore wrongly classified OUT_OF_WINDOW instead of WITHIN_WINDOW_DEFECTIVE.",
    "rationale": "I replaced the erroneous 'same calendar month' rule with the authoritative 30 calendar days from purchase date, explicitly noting that month boundaries do not matter. This ensures a defective, non-final-sale claim made 13 days after purchase is correctly classified WITHIN_WINDOW_DEFECTIVE. I preserved the prompt's structure, category list, ordering of checks, and the single-category JSON output contract, changing only the window definition and clarifying the defective-within-window case to match policy."
  },
  "verify": {
    "verifiedRun": {
      "id": "verify",
      "records": [
        {
          "stepId": "intake",
          "name": "Intake",
          "kind": "llm",
          "output": {
            "claim": {
              "orderId": "A-4471",
              "customer": "Northwind Traders",
              "item": "Standard Widget (not final sale)",
              "amount": 240,
              "purchaseDate": "2026-05-28",
              "requestDate": "2026-06-10",
              "reason": "Arrived defective — the unit will not power on."
            },
            "daysSincePurchase": 13,
            "defectClaimed": true,
            "finalSale": false
          },
          "live": true,
          "usage": {
            "input": 477,
            "output": 20
          }
        },
        {
          "stepId": "fraud_check",
          "name": "Fraud Check",
          "kind": "llm",
          "output": {
            "fraudRisk": "LOW",
            "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and there are no signals of identity mismatch, repeat abuse, or impossible timeline."
          },
          "live": true,
          "usage": {
            "input": 568,
            "output": 80
          }
        },
        {
          "stepId": "classify",
          "name": "Classifier",
          "kind": "llm",
          "output": {
            "category": "WITHIN_WINDOW_DEFECTIVE"
          },
          "live": true,
          "usage": {
            "input": 837,
            "output": 28
          }
        },
        {
          "stepId": "retrieve_policy",
          "name": "Policy Retriever",
          "kind": "rule",
          "output": {
            "policyRule": {
              "eligible": true,
              "note": "Defective within the 30-day window — full refund."
            }
          },
          "live": false
        },
        {
          "stepId": "eligibility",
          "name": "Eligibility",
          "kind": "rule",
          "output": {
            "eligible": true,
            "eligReason": "Defective within the 30-day window — full refund."
          },
          "live": false
        },
        {
          "stepId": "amount",
          "name": "Amount",
          "kind": "rule",
          "output": {
            "amount": 240
          },
          "live": false
        },
        {
          "stepId": "decision",
          "name": "Decision",
          "kind": "llm",
          "output": {
            "decision": "APPROVE",
            "rationale": "Your refund of $240 has been approved because the item was defective and returned within the 30-day window."
          },
          "live": true,
          "usage": {
            "input": 429,
            "output": 48
          }
        }
      ],
      "finalState": {
        "claim": {
          "orderId": "A-4471",
          "customer": "Northwind Traders",
          "item": "Standard Widget (not final sale)",
          "amount": 240,
          "purchaseDate": "2026-05-28",
          "requestDate": "2026-06-10",
          "reason": "Arrived defective — the unit will not power on."
        },
        "daysSincePurchase": 13,
        "defectClaimed": true,
        "finalSale": false,
        "fraudRisk": "LOW",
        "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and there are no signals of identity mismatch, repeat abuse, or impossible timeline.",
        "category": "WITHIN_WINDOW_DEFECTIVE",
        "policyRule": {
          "eligible": true,
          "note": "Defective within the 30-day window — full refund."
        },
        "eligible": true,
        "eligReason": "Defective within the 30-day window — full refund.",
        "amount": 240,
        "decision": "APPROVE",
        "rationale": "Your refund of $240 has been approved because the item was defective and returned within the 30-day window."
      },
      "outcome": {
        "decision": "APPROVE",
        "amount": 240,
        "pass": true
      }
    },
    "eval": {
      "passed": true,
      "before": {
        "decision": "DENY",
        "amount": 0
      },
      "after": {
        "decision": "APPROVE",
        "amount": 240
      },
      "assertion": "decision===\"APPROVE\" && amount===240"
    }
  },
  "usage": {
    "input": 10715,
    "output": 1639
  }
}) as unknown as LoopResult;
