import type { Lesson, PreventionResult, GateResult } from "./knowledge";

// AUTO-GENERATED by scripts/record.ts — real lessons + a real recurrence-prevention run + pre-ship gate.
export const RECORDED_LESSONS = ([
  {
    "id": "WL-001",
    "title": "Refund classifier used 'same calendar month' instead of the 30-day window",
    "failureClass": "wrong-policy-in-prompt",
    "agent": "refund-classifier",
    "culprit": "Classifier",
    "rootCause": "The prompt encoded an incorrect return-window rule. It defined the window as the 'SAME CALENDAR MONTH' as the purchase date, causing it to classify any cross-month request as OUT_OF_WINDOW. The authoritative policy defines the window as 30 calendar days from the purchase date, so a 13-day-old defective claim was wrongly marked OUT_OF_WINDOW instead of WITHIN_WINDOW_DEFECTIVE.",
    "repairSummary": "Replace the calendar-month rule with a 30-day window.",
    "patchedPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- The return window is 30 CALENDAR DAYS from the purchase date. A request is WITHIN the window if it is made 30 or fewer calendar days after the purchase date; it is OUT of the window if made more than 30 calendar days after the purchase date.\n- If the request is made more than 30 calendar days after the purchase date, classify OUT_OF_WINDOW.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the reason is change-of-mind with no defect, classify BUYER_REMORSE.\n- If the item is defective and the request is within the 30-day window (and the item is not final sale), classify WITHIN_WINDOW_DEFECTIVE.\n- Otherwise classify WITHIN_WINDOW_DEFECTIVE.",
    "evidence": {
      "before": "DENY · $0",
      "after": "APPROVE · $240"
    },
    "tags": [
      "policy",
      "date-window",
      "classification"
    ],
    "mintedAt": "2026-06-13",
    "protects": [
      "refund-classifier",
      "warranty-classifier",
      "returns-router"
    ]
  },
  {
    "id": "WL-002",
    "title": "Invoice extractor parsed DD/MM dates as MM/DD on EU invoices",
    "failureClass": "date-format-misparse",
    "agent": "invoice-extractor",
    "culprit": "Extractor",
    "rootCause": "Assumed US date format, producing wrong due dates and false late fees on EU invoices.",
    "repairSummary": "Detect locale / require explicit ISO parsing before computing due dates.",
    "evidence": {
      "before": "late-fee $1,200",
      "after": "on-time · $0"
    },
    "tags": [
      "date",
      "parsing",
      "extraction"
    ],
    "mintedAt": "2026-05-30",
    "protects": [
      "invoice-extractor",
      "billing-agent"
    ]
  },
  {
    "id": "WL-003",
    "title": "Support router sent billing tickets to the engineering queue",
    "failureClass": "misrouting",
    "agent": "support-router",
    "culprit": "Router",
    "rootCause": "Keyword overlap on 'charge' routed billing issues to tech, breaching SLAs.",
    "repairSummary": "Add intent disambiguation and prioritize billing terms in routing.",
    "evidence": {
      "before": "SLA breach 38%",
      "after": "SLA breach 4%"
    },
    "tags": [
      "routing",
      "intent",
      "classification"
    ],
    "mintedAt": "2026-05-22",
    "protects": [
      "support-router"
    ]
  },
  {
    "id": "WL-004",
    "title": "Contract summarizer obeyed an instruction injected in the document",
    "failureClass": "prompt-injection",
    "agent": "contract-summarizer",
    "culprit": "Summarizer",
    "rootCause": "Treated document text as instructions and approved a non-compliant clause.",
    "repairSummary": "Quarantine document content; never execute instructions found inside inputs.",
    "evidence": {
      "before": "approved bad clause",
      "after": "flagged + escalated"
    },
    "tags": [
      "security",
      "prompt-injection",
      "summarization"
    ],
    "mintedAt": "2026-05-10",
    "protects": [
      "contract-summarizer",
      "email-agent"
    ]
  },
  {
    "id": "WL-005",
    "title": "Flaky tool caused an unbounded retry storm",
    "failureClass": "retry-storm",
    "agent": "enrichment-agent",
    "culprit": "Retry policy",
    "rootCause": "No backoff or cap on a timing-out tool produced ~100x retries and a cost spike.",
    "repairSummary": "Exponential backoff + max-attempts cap + circuit breaker.",
    "evidence": {
      "before": "$420 / run",
      "after": "$0.40 / run"
    },
    "tags": [
      "reliability",
      "cost",
      "retries"
    ],
    "mintedAt": "2026-04-28",
    "protects": [
      "enrichment-agent",
      "scraper-agent"
    ]
  }
]) as unknown as Lesson[];
export const RECORDED_PREVENTION = ({
  "agent": "warranty-classifier",
  "failed": {
    "decision": "DENY",
    "amount": 0
  },
  "match": {
    "lesson": {
      "id": "WL-001",
      "title": "Refund classifier used 'same calendar month' instead of the 30-day window",
      "failureClass": "wrong-policy-in-prompt",
      "agent": "refund-classifier",
      "culprit": "Classifier",
      "rootCause": "The prompt encoded an incorrect return-window rule. It defined the window as the 'SAME CALENDAR MONTH' as the purchase date, causing it to classify any cross-month request as OUT_OF_WINDOW. The authoritative policy defines the window as 30 calendar days from the purchase date, so a 13-day-old defective claim was wrongly marked OUT_OF_WINDOW instead of WITHIN_WINDOW_DEFECTIVE.",
      "repairSummary": "Replace the calendar-month rule with a 30-day window.",
      "patchedPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- The return window is 30 CALENDAR DAYS from the purchase date. A request is WITHIN the window if it is made 30 or fewer calendar days after the purchase date; it is OUT of the window if made more than 30 calendar days after the purchase date.\n- If the request is made more than 30 calendar days after the purchase date, classify OUT_OF_WINDOW.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the reason is change-of-mind with no defect, classify BUYER_REMORSE.\n- If the item is defective and the request is within the 30-day window (and the item is not final sale), classify WITHIN_WINDOW_DEFECTIVE.\n- Otherwise classify WITHIN_WINDOW_DEFECTIVE.",
      "evidence": {
        "before": "DENY · $0",
        "after": "APPROVE · $240"
      },
      "tags": [
        "policy",
        "date-window",
        "classification"
      ],
      "mintedAt": "2026-06-13",
      "protects": [
        "refund-classifier",
        "warranty-classifier",
        "returns-router"
      ]
    },
    "confidence": 0.78,
    "rationale": "The warranty classifier wrongly marked a 13-day-old purchase as OUT_OF_WINDOW, mirroring WL-001's mechanism: a policy/date-window misconfiguration in the classifier causing items within the valid window to be classified as outside it. Same underlying failure (wrong date-window policy in classification logic), different domain."
  },
  "prevented": {
    "decision": "APPROVE",
    "amount": 520,
    "pass": true
  },
  "usage": {
    "input": 5561,
    "output": 498
  }
}) as unknown as PreventionResult;
export const RECORDED_GATE = ([
  {
    "candidate": {
      "agent": "refund-classifier",
      "label": "v2.1 — 'within the billing period' rule",
      "promptSnippet": "A return is valid only if it is filed within the same billing period as the purchase, where each period runs from the 1st to the last day of a month."
    },
    "checks": [
      {
        "lessonId": "WL-001",
        "failureClass": "wrong-policy-in-prompt",
        "risk": "high",
        "why": "This repeats the exact root-cause mechanism from WL-001: the prompt encodes a calendar-month/billing-period window instead of the authoritative 30-calendar-days-from-purchase rule. Same agent, same failure class (wrong-policy-in-prompt), and it would again wrongly classify cross-month requests as out-of-window."
      },
      {
        "lessonId": "WL-002",
        "failureClass": "date-format-misparse",
        "risk": "low",
        "why": "Different agent and failure class (refund-classifier vs invoice-extractor date-misparse). However, the rule involves date handling and billing periods, which could touch on date-parsing ambiguity; root-cause mechanism (locale date-format assumption) is not directly repeated, but timezone/period-boundary edge cases warrant mild caution."
      },
      {
        "lessonId": "WL-003",
        "failureClass": "misrouting",
        "risk": "none",
        "why": "The lesson concerns keyword-overlap misrouting in support-router. This change is a refund-classifier validity rule about billing periods, with no routing logic or keyword-overlap mechanism. Different agent and failure class; no reintroduction of the root cause."
      },
      {
        "lessonId": "WL-004",
        "failureClass": "prompt-injection",
        "risk": "none",
        "why": "The lesson concerns prompt-injection in a contract-summarizer treating document text as instructions. The candidate change is a refund-classifier business rule about return timing windows; it does not involve ingesting untrusted document text as instructions, so it does not repeat the root-cause mechanism."
      },
      {
        "lessonId": "WL-005",
        "failureClass": "retry-storm",
        "risk": "none",
        "why": "The candidate change is a business-logic rule about return validity windows for a refund-classifier, unrelated to retry/backoff mechanics. It does not touch tool retry behavior, so it cannot reintroduce the retry-storm failure class from WL-005."
      }
    ],
    "gate": "BLOCK",
    "blockedBy": [
      "WL-001"
    ],
    "usage": {
      "input": 2819,
      "output": 542
    }
  },
  {
    "candidate": {
      "agent": "refund-classifier",
      "label": "v2.2 — explicit 30-day window",
      "promptSnippet": "A return is valid if requested within 30 calendar days of the purchase date, regardless of any month boundary."
    },
    "checks": [
      {
        "lessonId": "WL-001",
        "failureClass": "wrong-policy-in-prompt",
        "risk": "none",
        "why": "The candidate change correctly encodes the authoritative 30-calendar-day rule and explicitly removes the month-boundary dependency that caused WL-001. It fixes the root cause rather than reintroducing it."
      },
      {
        "lessonId": "WL-002",
        "failureClass": "date-format-misparse",
        "risk": "low",
        "why": "Different agent (refund-classifier vs invoice-extractor) and the rule uses calendar-day arithmetic rather than parsing locale-specific date strings. However, computing 30 days from a purchase date still depends on correctly parsing dates; if input dates are ambiguous US/EU formats, the same misparse root cause could affect day-count calculations. The rule itself doesn't address date parsing, so residual but not direct risk."
      },
      {
        "lessonId": "WL-003",
        "failureClass": "misrouting",
        "risk": "none",
        "why": "The candidate change concerns a refund-classifier's return-window validity rule based on calendar days, which is unrelated to the lesson's root cause of keyword-overlap misrouting in the support-router agent. Different agent, different failure class, and no shared root-cause mechanism."
      },
      {
        "lessonId": "WL-004",
        "failureClass": "prompt-injection",
        "risk": "none",
        "why": "The candidate change is a deterministic refund-classification rule for a different agent and does not involve treating untrusted document text as instructions, so it does not reintroduce the prompt-injection root cause from WL-004."
      },
      {
        "lessonId": "WL-005",
        "failureClass": "retry-storm",
        "risk": "none",
        "why": "The candidate change is a business logic rule about refund validity windows for the refund-classifier agent. It has no connection to retry behavior, backoff, or tool timeouts—the root cause of the WL-005 retry-storm lesson. Different agent, different failure mechanism."
      }
    ],
    "gate": "PASS",
    "blockedBy": [],
    "usage": {
      "input": 2779,
      "output": 513
    }
  }
]) as unknown as GateResult[];
