import type { LoopResult } from "./types";

// AUTO-GENERATED by scripts/record.ts — a REAL captured WorldLine run (live Opus 4.8).
// Used as the instant, reliable demo default; "Re-run live" recomputes via /api/loop.
export const RECORDED = ({
  "base": {
    "id": "base",
    "records": [
      {
        "stepId": "intake",
        "name": "Intake",
        "kind": "llm",
        "output": {
          "claim": {
            "orderId": "A-4471",
            "customer": "Northwind Traders",
            "item": "Standard Widget (not final sale)",
            "amount": 240,
            "purchaseDate": "2026-05-28",
            "requestDate": "2026-06-10",
            "reason": "Arrived defective — the unit will not power on."
          },
          "daysSincePurchase": 13,
          "defectClaimed": true,
          "finalSale": false
        },
        "live": true,
        "usage": {
          "input": 477,
          "output": 20
        }
      },
      {
        "stepId": "fraud_check",
        "name": "Fraud Check",
        "kind": "llm",
        "output": {
          "fraudRisk": "LOW",
          "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and there are no concrete fraud signals such as identity mismatch, repeat abuse, or an impossible timeline."
        },
        "live": true,
        "usage": {
          "input": 568,
          "output": 88
        }
      },
      {
        "stepId": "classify",
        "name": "Classifier",
        "kind": "llm",
        "output": {
          "category": "OUT_OF_WINDOW"
        },
        "live": true,
        "usage": {
          "input": 732,
          "output": 20
        }
      },
      {
        "stepId": "retrieve_policy",
        "name": "Policy Retriever",
        "kind": "rule",
        "output": {
          "policyRule": {
            "eligible": false,
            "note": "Return window (30 days) has passed."
          }
        },
        "live": false
      },
      {
        "stepId": "eligibility",
        "name": "Eligibility",
        "kind": "rule",
        "output": {
          "eligible": false,
          "eligReason": "Return window (30 days) has passed."
        },
        "live": false
      },
      {
        "stepId": "amount",
        "name": "Amount",
        "kind": "rule",
        "output": {
          "amount": 0
        },
        "live": false
      },
      {
        "stepId": "decision",
        "name": "Decision",
        "kind": "llm",
        "output": {
          "decision": "DENY",
          "rationale": "Unfortunately, your refund request cannot be approved because the item falls outside our 30-day return window."
        },
        "live": true,
        "usage": {
          "input": 418,
          "output": 49
        }
      }
    ],
    "finalState": {
      "claim": {
        "orderId": "A-4471",
        "customer": "Northwind Traders",
        "item": "Standard Widget (not final sale)",
        "amount": 240,
        "purchaseDate": "2026-05-28",
        "requestDate": "2026-06-10",
        "reason": "Arrived defective — the unit will not power on."
      },
      "daysSincePurchase": 13,
      "defectClaimed": true,
      "finalSale": false,
      "fraudRisk": "LOW",
      "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and there are no concrete fraud signals such as identity mismatch, repeat abuse, or an impossible timeline.",
      "category": "OUT_OF_WINDOW",
      "policyRule": {
        "eligible": false,
        "note": "Return window (30 days) has passed."
      },
      "eligible": false,
      "eligReason": "Return window (30 days) has passed.",
      "amount": 0,
      "decision": "DENY",
      "rationale": "Unfortunately, your refund request cannot be approved because the item falls outside our 30-day return window."
    },
    "outcome": {
      "decision": "DENY",
      "amount": 0,
      "pass": false
    }
  },
  "bisect": {
    "evidence": [
      {
        "nodeId": "intake",
        "name": "Intake",
        "correct": true,
        "reason": "Days from 2026-05-28 to 2026-06-10 is 13 days, defectClaimed true matches the reason, finalSale false matches the item description. All fields correctly extracted.",
        "intervened": false,
        "flipped": false
      },
      {
        "nodeId": "fraud_check",
        "name": "Fraud Check",
        "correct": true,
        "reason": "The fraud check correctly assesses LOW risk: timeline is consistent (13 days, within window), item not final sale, defective claim is ordinary, and no fraud signals present. The output is consistent with its input.",
        "intervened": false,
        "flipped": false
      },
      {
        "nodeId": "classify",
        "name": "Classifier",
        "correct": false,
        "reason": "Input shows 13 days since purchase (within 30-day window), defect claimed, not final sale. This should be WITHIN_WINDOW_DEFECTIVE, not OUT_OF_WINDOW.",
        "correctOutput": {
          "category": "WITHIN_WINDOW_DEFECTIVE"
        },
        "intervened": true,
        "flipped": true
      },
      {
        "nodeId": "decision",
        "name": "Decision",
        "correct": false,
        "reason": "The decision step itself relies on the eligibility input (eligible:false, category OUT_OF_WINDOW). However, the input state is internally contradictory and the decision step contradicts the actual facts present in its own input: daysSincePurchase is 13, which is clearly within the 30-day window, and the item is defective and not final sale. The decision step's rationale states the item is outside the 30-day window, which is false given daysSincePurchase=13 in its own input. A correct decision given the actual input facts (13 days, defective, not final sale) should APPROVE a full refund.",
        "correctOutput": {
          "decision": "APPROVE",
          "rationale": "Your refund request is approved. The item arrived defective within the 30-day return window (13 days since purchase) and is not a final-sale item, qualifying for a full refund of $240."
        },
        "intervened": true,
        "flipped": false
      }
    ],
    "culpritId": "classify",
    "culpritName": "Classifier",
    "forkRun": {
      "id": "bisect-classify",
      "records": [
        {
          "stepId": "intake",
          "name": "Intake",
          "kind": "llm",
          "output": {
            "claim": {
              "orderId": "A-4471",
              "customer": "Northwind Traders",
              "item": "Standard Widget (not final sale)",
              "amount": 240,
              "purchaseDate": "2026-05-28",
              "requestDate": "2026-06-10",
              "reason": "Arrived defective — the unit will not power on."
            },
            "daysSincePurchase": 13,
            "defectClaimed": true,
            "finalSale": false
          },
          "live": false,
          "usage": {
            "input": 477,
            "output": 20
          },
          "cached": true
        },
        {
          "stepId": "fraud_check",
          "name": "Fraud Check",
          "kind": "llm",
          "output": {
            "fraudRisk": "LOW",
            "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and there are no concrete fraud signals such as identity mismatch, repeat abuse, or an impossible timeline."
          },
          "live": false,
          "usage": {
            "input": 568,
            "output": 88
          },
          "cached": true
        },
        {
          "stepId": "classify",
          "name": "Classifier",
          "kind": "llm",
          "output": {
            "category": "WITHIN_WINDOW_DEFECTIVE"
          },
          "live": false,
          "forked": true
        },
        {
          "stepId": "retrieve_policy",
          "name": "Policy Retriever",
          "kind": "rule",
          "output": {
            "policyRule": {
              "eligible": true,
              "note": "Defective within the 30-day window — full refund."
            }
          },
          "live": false
        },
        {
          "stepId": "eligibility",
          "name": "Eligibility",
          "kind": "rule",
          "output": {
            "eligible": true,
            "eligReason": "Defective within the 30-day window — full refund."
          },
          "live": false
        },
        {
          "stepId": "amount",
          "name": "Amount",
          "kind": "rule",
          "output": {
            "amount": 240
          },
          "live": false
        },
        {
          "stepId": "decision",
          "name": "Decision",
          "kind": "llm",
          "output": {
            "decision": "APPROVE",
            "rationale": "Your refund of $240 has been approved because the item was defective and returned within the 30-day eligibility window."
          },
          "live": true,
          "usage": {
            "input": 429,
            "output": 52
          }
        }
      ],
      "finalState": {
        "claim": {
          "orderId": "A-4471",
          "customer": "Northwind Traders",
          "item": "Standard Widget (not final sale)",
          "amount": 240,
          "purchaseDate": "2026-05-28",
          "requestDate": "2026-06-10",
          "reason": "Arrived defective — the unit will not power on."
        },
        "daysSincePurchase": 13,
        "defectClaimed": true,
        "finalSale": false,
        "fraudRisk": "LOW",
        "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and there are no concrete fraud signals such as identity mismatch, repeat abuse, or an impossible timeline.",
        "category": "WITHIN_WINDOW_DEFECTIVE",
        "policyRule": {
          "eligible": true,
          "note": "Defective within the 30-day window — full refund."
        },
        "eligible": true,
        "eligReason": "Defective within the 30-day window — full refund.",
        "amount": 240,
        "decision": "APPROVE",
        "rationale": "Your refund of $240 has been approved because the item was defective and returned within the 30-day eligibility window."
      },
      "outcome": {
        "decision": "APPROVE",
        "amount": 240,
        "pass": true
      }
    }
  },
  "repair": {
    "nodeId": "classify",
    "nodeName": "Classifier",
    "originalPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- A return is valid ONLY if the request is made in the SAME CALENDAR MONTH as the purchase. If the request month differs from the purchase month, classify OUT_OF_WINDOW.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the reason is change-of-mind with no defect, classify BUYER_REMORSE.\n- Otherwise classify WITHIN_WINDOW_DEFECTIVE.",
    "patchedPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- The return window is 30 CALENDAR DAYS from the purchase date. A request is within the window if the number of days from the purchase date to the request date is 30 or fewer; if it is more than 30 days, the request is outside the window.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the request is made more than 30 days after the purchase date, classify OUT_OF_WINDOW.\n- If the reason is change-of-mind with no defect, classify BUYER_REMORSE.\n- Otherwise (a defect is claimed, the request is within the 30-day window, and the item is not final sale), classify WITHIN_WINDOW_DEFECTIVE.",
    "rootCause": "The prompt encoded an incorrect return-window rule. It instructed the classifier to treat a return as valid only if made in the SAME CALENDAR MONTH as the purchase, classifying anything in a different month as OUT_OF_WINDOW. The authoritative policy defines the window as 30 CALENDAR DAYS from the purchase date. A claim 13 days after purchase (with a defect, not final sale) is within the window, but the calendar-month rule could mark it OUT_OF_WINDOW (e.g., a purchase late in one month and a request early the next month spanning fewer than 30 days), producing the wrong classification.",
    "rationale": "The only substantive defect was the window rule. I replaced the SAME CALENDAR MONTH test with the authoritative 30-CALENDAR-DAY test, defining within-window as 30 or fewer days from purchase and OUT_OF_WINDOW as more than 30 days. The other category rules (FINAL_SALE, BUYER_REMORSE, and the default WITHIN_WINDOW_DEFECTIVE) were preserved and clarified to reflect that a defective, non-final-sale item within 30 days yields a full refund. Structure, category list, and the JSON output contract are unchanged. Under this corrected prompt, a 13-day-old defective, non-final-sale claim is correctly classified as WITHIN_WINDOW_DEFECTIVE."
  },
  "verify": {
    "verifiedRun": {
      "id": "verify",
      "records": [
        {
          "stepId": "intake",
          "name": "Intake",
          "kind": "llm",
          "output": {
            "claim": {
              "orderId": "A-4471",
              "customer": "Northwind Traders",
              "item": "Standard Widget (not final sale)",
              "amount": 240,
              "purchaseDate": "2026-05-28",
              "requestDate": "2026-06-10",
              "reason": "Arrived defective — the unit will not power on."
            },
            "daysSincePurchase": 13,
            "defectClaimed": true,
            "finalSale": false
          },
          "live": true,
          "usage": {
            "input": 477,
            "output": 20
          }
        },
        {
          "stepId": "fraud_check",
          "name": "Fraud Check",
          "kind": "llm",
          "output": {
            "fraudRisk": "LOW",
            "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and no signals of identity mismatch, repeat abuse, or impossible timeline."
          },
          "live": true,
          "usage": {
            "input": 568,
            "output": 78
          }
        },
        {
          "stepId": "classify",
          "name": "Classifier",
          "kind": "llm",
          "output": {
            "category": "WITHIN_WINDOW_DEFECTIVE"
          },
          "live": true,
          "usage": {
            "input": 805,
            "output": 28
          }
        },
        {
          "stepId": "retrieve_policy",
          "name": "Policy Retriever",
          "kind": "rule",
          "output": {
            "policyRule": {
              "eligible": true,
              "note": "Defective within the 30-day window — full refund."
            }
          },
          "live": false
        },
        {
          "stepId": "eligibility",
          "name": "Eligibility",
          "kind": "rule",
          "output": {
            "eligible": true,
            "eligReason": "Defective within the 30-day window — full refund."
          },
          "live": false
        },
        {
          "stepId": "amount",
          "name": "Amount",
          "kind": "rule",
          "output": {
            "amount": 240
          },
          "live": false
        },
        {
          "stepId": "decision",
          "name": "Decision",
          "kind": "llm",
          "output": {
            "decision": "APPROVE",
            "rationale": "Your refund of $240 has been approved because your item was defective and returned within the 30-day eligibility window."
          },
          "live": true,
          "usage": {
            "input": 429,
            "output": 52
          }
        }
      ],
      "finalState": {
        "claim": {
          "orderId": "A-4471",
          "customer": "Northwind Traders",
          "item": "Standard Widget (not final sale)",
          "amount": 240,
          "purchaseDate": "2026-05-28",
          "requestDate": "2026-06-10",
          "reason": "Arrived defective — the unit will not power on."
        },
        "daysSincePurchase": 13,
        "defectClaimed": true,
        "finalSale": false,
        "fraudRisk": "LOW",
        "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and no signals of identity mismatch, repeat abuse, or impossible timeline.",
        "category": "WITHIN_WINDOW_DEFECTIVE",
        "policyRule": {
          "eligible": true,
          "note": "Defective within the 30-day window — full refund."
        },
        "eligible": true,
        "eligReason": "Defective within the 30-day window — full refund.",
        "amount": 240,
        "decision": "APPROVE",
        "rationale": "Your refund of $240 has been approved because your item was defective and returned within the 30-day eligibility window."
      },
      "outcome": {
        "decision": "APPROVE",
        "amount": 240,
        "pass": true
      }
    },
    "eval": {
      "passed": true,
      "before": {
        "decision": "DENY",
        "amount": 0
      },
      "after": {
        "decision": "APPROVE",
        "amount": 240
      },
      "assertion": "decision===\"APPROVE\" && amount===240"
    }
  },
  "usage": {
    "input": 12488,
    "output": 2032
  }
}) as unknown as LoopResult;
