import type { Lesson, PreventionResult, GateResult } from "./knowledge";

// AUTO-GENERATED by scripts/record.ts — real lessons + a real recurrence-prevention run + pre-ship gate.
export const RECORDED_LESSONS = ([
  {
    "id": "WL-001",
    "title": "Refund classifier used 'same calendar month' instead of the 30-day window",
    "failureClass": "wrong-policy-in-prompt",
    "agent": "refund-classifier",
    "culprit": "Classifier",
    "rootCause": "The prompt encodes an incorrect return-window rule. It instructs the classifier to treat a return as valid only within the SAME CALENDAR MONTH as the purchase, and to classify OUT_OF_WINDOW whenever the request month differs from the purchase month. The authoritative policy actually defines the window as 30 CALENDAR DAYS from the purchase date. This caused a request made 13 days after purchase (which spanned into a different calendar month) to be wrongly classified as OUT_OF_WINDOW instead of WITHIN_WINDOW_DEFECTIVE.",
    "repairSummary": "Replace the calendar-month rule with a 30-day window.",
    "patchedPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- The return window is 30 CALENDAR DAYS from the purchase date. A request is WITHIN the window if it is made on or before the 30th calendar day after the purchase date; it is outside the window if made after 30 days. Do NOT use calendar months to determine the window.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the request is made more than 30 calendar days after the purchase date, classify OUT_OF_WINDOW.\n- If the reason is change-of-mind with no defect (and the item is not final sale), classify BUYER_REMORSE.\n- If the item is defective on arrival and the request is within the 30-day window (and the item is not final sale), classify WITHIN_WINDOW_DEFECTIVE.",
    "evidence": {
      "before": "DENY · $0",
      "after": "APPROVE · $240"
    },
    "tags": [
      "policy",
      "date-window",
      "classification"
    ],
    "mintedAt": "2026-06-13",
    "protects": [
      "refund-classifier",
      "warranty-classifier",
      "returns-router"
    ]
  },
  {
    "id": "WL-002",
    "title": "Invoice extractor parsed DD/MM dates as MM/DD on EU invoices",
    "failureClass": "date-format-misparse",
    "agent": "invoice-extractor",
    "culprit": "Extractor",
    "rootCause": "Assumed US date format, producing wrong due dates and false late fees on EU invoices.",
    "repairSummary": "Detect locale / require explicit ISO parsing before computing due dates.",
    "evidence": {
      "before": "late-fee $1,200",
      "after": "on-time · $0"
    },
    "tags": [
      "date",
      "parsing",
      "extraction"
    ],
    "mintedAt": "2026-05-30",
    "protects": [
      "invoice-extractor",
      "billing-agent"
    ]
  },
  {
    "id": "WL-003",
    "title": "Support router sent billing tickets to the engineering queue",
    "failureClass": "misrouting",
    "agent": "support-router",
    "culprit": "Router",
    "rootCause": "Keyword overlap on 'charge' routed billing issues to tech, breaching SLAs.",
    "repairSummary": "Add intent disambiguation and prioritize billing terms in routing.",
    "evidence": {
      "before": "SLA breach 38%",
      "after": "SLA breach 4%"
    },
    "tags": [
      "routing",
      "intent",
      "classification"
    ],
    "mintedAt": "2026-05-22",
    "protects": [
      "support-router"
    ]
  },
  {
    "id": "WL-004",
    "title": "Contract summarizer obeyed an instruction injected in the document",
    "failureClass": "prompt-injection",
    "agent": "contract-summarizer",
    "culprit": "Summarizer",
    "rootCause": "Treated document text as instructions and approved a non-compliant clause.",
    "repairSummary": "Quarantine document content; never execute instructions found inside inputs.",
    "evidence": {
      "before": "approved bad clause",
      "after": "flagged + escalated"
    },
    "tags": [
      "security",
      "prompt-injection",
      "summarization"
    ],
    "mintedAt": "2026-05-10",
    "protects": [
      "contract-summarizer",
      "email-agent"
    ]
  },
  {
    "id": "WL-005",
    "title": "Flaky tool caused an unbounded retry storm",
    "failureClass": "retry-storm",
    "agent": "enrichment-agent",
    "culprit": "Retry policy",
    "rootCause": "No backoff or cap on a timing-out tool produced ~100x retries and a cost spike.",
    "repairSummary": "Exponential backoff + max-attempts cap + circuit breaker.",
    "evidence": {
      "before": "$420 / run",
      "after": "$0.40 / run"
    },
    "tags": [
      "reliability",
      "cost",
      "retries"
    ],
    "mintedAt": "2026-04-28",
    "protects": [
      "enrichment-agent",
      "scraper-agent"
    ]
  }
]) as unknown as Lesson[];
export const RECORDED_PREVENTION = ({
  "agent": "warranty-classifier",
  "failed": {
    "decision": "DENY",
    "amount": 0
  },
  "match": {
    "lesson": {
      "id": "WL-001",
      "title": "Refund classifier used 'same calendar month' instead of the 30-day window",
      "failureClass": "wrong-policy-in-prompt",
      "agent": "refund-classifier",
      "culprit": "Classifier",
      "rootCause": "The prompt encodes an incorrect return-window rule. It instructs the classifier to treat a return as valid only within the SAME CALENDAR MONTH as the purchase, and to classify OUT_OF_WINDOW whenever the request month differs from the purchase month. The authoritative policy actually defines the window as 30 CALENDAR DAYS from the purchase date. This caused a request made 13 days after purchase (which spanned into a different calendar month) to be wrongly classified as OUT_OF_WINDOW instead of WITHIN_WINDOW_DEFECTIVE.",
      "repairSummary": "Replace the calendar-month rule with a 30-day window.",
      "patchedPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- The return window is 30 CALENDAR DAYS from the purchase date. A request is WITHIN the window if it is made on or before the 30th calendar day after the purchase date; it is outside the window if made after 30 days. Do NOT use calendar months to determine the window.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the request is made more than 30 calendar days after the purchase date, classify OUT_OF_WINDOW.\n- If the reason is change-of-mind with no defect (and the item is not final sale), classify BUYER_REMORSE.\n- If the item is defective on arrival and the request is within the 30-day window (and the item is not final sale), classify WITHIN_WINDOW_DEFECTIVE.",
      "evidence": {
        "before": "DENY · $0",
        "after": "APPROVE · $240"
      },
      "tags": [
        "policy",
        "date-window",
        "classification"
      ],
      "mintedAt": "2026-06-13",
      "protects": [
        "refund-classifier",
        "warranty-classifier",
        "returns-router"
      ]
    },
    "confidence": 0.78,
    "rationale": "Both failures involve a classifier applying a wrong date-window policy. Here a 13-day-old purchase was marked OUT_OF_WINDOW, suggesting the warranty window logic is misconfigured—analogous to WL-001's incorrect date-window interpretation in the classification prompt. The mechanism (wrong policy/window encoded in classifier) matches, though domain differs (warranty vs refund)."
  },
  "prevented": {
    "decision": "APPROVE",
    "amount": 520,
    "pass": true
  },
  "usage": {
    "input": 5520,
    "output": 510
  }
}) as unknown as PreventionResult;
export const RECORDED_GATE = ([
  {
    "candidate": {
      "agent": "refund-classifier",
      "label": "v2.1 — 'current calendar month' rule",
      "promptSnippet": "A return is valid only if it is requested during the same calendar month as the purchase; requests in any later month are OUT_OF_WINDOW."
    },
    "checks": [
      {
        "lessonId": "WL-001",
        "failureClass": "wrong-policy-in-prompt",
        "risk": "high",
        "why": "The candidate reintroduces the exact root cause from WL-001: encoding a same-calendar-month return rule instead of the authoritative 30-calendar-day window, on the same refund-classifier agent. This would again misclassify in-window requests that span month boundaries as OUT_OF_WINDOW."
      },
      {
        "lessonId": "WL-002",
        "failureClass": "date-format-misparse",
        "risk": "none",
        "why": "The lesson concerns date-format misparsing (US vs EU) in an invoice-extractor. The candidate change is a different agent (refund-classifier) with a calendar-month window rule, which doesn't involve parsing ambiguous date formats. No shared root-cause mechanism, though a separate edge case (month-boundary fairness) exists outside this lesson's scope."
      },
      {
        "lessonId": "WL-003",
        "failureClass": "misrouting",
        "risk": "none",
        "why": "The lesson concerns keyword-overlap misrouting in a support-router. The candidate change is a refund-classifier window rule with no routing or keyword-matching mechanism, so it does not repeat the lesson's root cause."
      },
      {
        "lessonId": "WL-004",
        "failureClass": "prompt-injection",
        "risk": "none",
        "why": "The lesson concerns prompt-injection in a contract-summarizer (treating document text as instructions). The candidate change is a deterministic refund-window business rule for a different agent with no mechanism for ingesting or acting on untrusted text as instructions. No reintroduction of the prompt-injection root cause."
      },
      {
        "lessonId": "WL-005",
        "failureClass": "retry-storm",
        "risk": "none",
        "why": "The candidate change is a business-logic rule about return validity windows for a refund-classifier agent. It has nothing to do with retry behavior, backoff, or tool timeouts, so it does not reintroduce the retry-storm failure class."
      }
    ],
    "gate": "BLOCK",
    "blockedBy": [
      "WL-001"
    ],
    "usage": {
      "input": 2872,
      "output": 528
    }
  },
  {
    "candidate": {
      "agent": "refund-classifier",
      "label": "v2.2 — explicit 30-day window",
      "promptSnippet": "A return is valid if requested within 30 calendar days of the purchase date, regardless of any month boundary."
    },
    "checks": [
      {
        "lessonId": "WL-001",
        "failureClass": "wrong-policy-in-prompt",
        "risk": "none",
        "why": "The candidate change explicitly corrects the root cause by defining the window as 30 calendar days from purchase date regardless of month boundary, which is the authoritative policy. It does not reintroduce the calendar-month error."
      },
      {
        "lessonId": "WL-002",
        "failureClass": "date-format-misparse",
        "risk": "low",
        "why": "Different agent and failure class; this rule involves date arithmetic (30-day window) rather than parsing ambiguous date formats. The root cause (locale-based date format assumption) isn't directly repeated, but any date handling carries some residual misparse risk if input dates aren't normalized."
      },
      {
        "lessonId": "WL-003",
        "failureClass": "misrouting",
        "risk": "none",
        "why": "The lesson concerns keyword-overlap misrouting in the support-router agent. This change is for a different agent (refund-classifier) and addresses date-window validity for returns, with no routing or keyword-overlap mechanism. It does not repeat the lesson's root cause."
      },
      {
        "lessonId": "WL-004",
        "failureClass": "prompt-injection",
        "risk": "none",
        "why": "The candidate change is a refund-classifier business rule about return windows, unrelated to the contract-summarizer prompt-injection lesson. It does not treat document text as instructions or share the root-cause mechanism."
      },
      {
        "lessonId": "WL-005",
        "failureClass": "retry-storm",
        "risk": "none",
        "why": "The candidate change is a business-logic rule for refund validity in a different agent (refund-classifier) and has nothing to do with retry behavior, backoff, or tool timeouts. It does not repeat the retry-storm root-cause mechanism."
      }
    ],
    "gate": "PASS",
    "blockedBy": [],
    "usage": {
      "input": 2817,
      "output": 457
    }
  }
]) as unknown as GateResult[];
