import type { LoopResult } from "./types";

// AUTO-GENERATED by scripts/record.ts — a REAL captured WorldLine run (live Opus 4.8).
// Used as the instant, reliable demo default; "Re-run live" recomputes via /api/loop.
export const RECORDED = ({
  "base": {
    "id": "base",
    "records": [
      {
        "stepId": "intake",
        "name": "Intake",
        "kind": "llm",
        "output": {
          "claim": {
            "orderId": "A-4471",
            "customer": "Northwind Traders",
            "item": "Standard Widget (not final sale)",
            "amount": 240,
            "purchaseDate": "2026-05-28",
            "requestDate": "2026-06-10",
            "reason": "Arrived defective — the unit will not power on."
          },
          "daysSincePurchase": 13,
          "defectClaimed": true,
          "finalSale": false
        },
        "live": true,
        "usage": {
          "input": 477,
          "output": 20
        }
      },
      {
        "stepId": "fraud_check",
        "name": "Fraud Check",
        "kind": "llm",
        "output": {
          "fraudRisk": "LOW",
          "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item not final sale, no signs of repeat abuse, identity mismatch, or impossible timeline."
        },
        "live": true,
        "usage": {
          "input": 568,
          "output": 76
        }
      },
      {
        "stepId": "classify",
        "name": "Classifier",
        "kind": "llm",
        "output": {
          "category": "OUT_OF_WINDOW"
        },
        "live": true,
        "usage": {
          "input": 732,
          "output": 20
        }
      },
      {
        "stepId": "retrieve_policy",
        "name": "Policy Retriever",
        "kind": "rule",
        "output": {
          "policyRule": {
            "eligible": false,
            "note": "Return window (30 days) has passed."
          }
        },
        "live": false
      },
      {
        "stepId": "eligibility",
        "name": "Eligibility",
        "kind": "rule",
        "output": {
          "eligible": false,
          "eligReason": "Return window (30 days) has passed."
        },
        "live": false
      },
      {
        "stepId": "amount",
        "name": "Amount",
        "kind": "rule",
        "output": {
          "amount": 0
        },
        "live": false
      },
      {
        "stepId": "decision",
        "name": "Decision",
        "kind": "llm",
        "output": {
          "decision": "DENY",
          "rationale": "Unfortunately, your refund cannot be approved because the request falls outside our 30-day return window."
        },
        "live": true,
        "usage": {
          "input": 418,
          "output": 48
        }
      }
    ],
    "finalState": {
      "claim": {
        "orderId": "A-4471",
        "customer": "Northwind Traders",
        "item": "Standard Widget (not final sale)",
        "amount": 240,
        "purchaseDate": "2026-05-28",
        "requestDate": "2026-06-10",
        "reason": "Arrived defective — the unit will not power on."
      },
      "daysSincePurchase": 13,
      "defectClaimed": true,
      "finalSale": false,
      "fraudRisk": "LOW",
      "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item not final sale, no signs of repeat abuse, identity mismatch, or impossible timeline.",
      "category": "OUT_OF_WINDOW",
      "policyRule": {
        "eligible": false,
        "note": "Return window (30 days) has passed."
      },
      "eligible": false,
      "eligReason": "Return window (30 days) has passed.",
      "amount": 0,
      "decision": "DENY",
      "rationale": "Unfortunately, your refund cannot be approved because the request falls outside our 30-day return window."
    },
    "outcome": {
      "decision": "DENY",
      "amount": 0,
      "pass": false
    }
  },
  "bisect": {
    "evidence": [
      {
        "nodeId": "intake",
        "name": "Intake",
        "correct": true,
        "reason": "Days from 2026-05-28 to 2026-06-10 is 13 days, defectClaimed=true matches reason, finalSale=false matches item description. All fields correctly extracted.",
        "intervened": true,
        "flipped": false,
        "probedTo": "finalSale → true",
        "result": {
          "decision": "DENY",
          "amount": 0
        }
      },
      {
        "nodeId": "fraud_check",
        "name": "Fraud Check",
        "correct": true,
        "reason": "The fraud check assessment is reasonable given the input: 13 days since purchase (within window), defective claim, not final sale, no signs of abuse or timeline impossibility. LOW risk is appropriate.",
        "intervened": true,
        "flipped": false,
        "probedTo": "fraudRisk → HIGH",
        "result": {
          "decision": "DENY",
          "amount": 0
        }
      },
      {
        "nodeId": "classify",
        "name": "Classifier",
        "correct": false,
        "reason": "The claim is within the 30-day window (13 days), item is defective and not final sale, so it should be classified WITHIN_WINDOW_DEFECTIVE, not OUT_OF_WINDOW.",
        "correctOutput": {
          "category": "WITHIN_WINDOW_DEFECTIVE"
        },
        "intervened": true,
        "flipped": true,
        "probedTo": "category → WITHIN_WINDOW_DEFECTIVE",
        "result": {
          "decision": "APPROVE",
          "amount": 240
        }
      },
      {
        "nodeId": "decision",
        "name": "Decision",
        "correct": true,
        "reason": "The decision step correctly applied its input: category was OUT_OF_WINDOW, eligible was false, amount 0. Given that input, DENY with the matching rationale is the correct output. The upstream categorization is wrong (13 days is within the 30-day window), but that is not this step's fault — its own output is consistent with its input.",
        "intervened": true,
        "flipped": false,
        "probedTo": "force APPROVE",
        "result": {
          "decision": "APPROVE",
          "amount": 0
        }
      }
    ],
    "culpritId": "classify",
    "culpritName": "Classifier",
    "forkRun": {
      "id": "bisect-classify",
      "records": [
        {
          "stepId": "intake",
          "name": "Intake",
          "kind": "llm",
          "output": {
            "claim": {
              "orderId": "A-4471",
              "customer": "Northwind Traders",
              "item": "Standard Widget (not final sale)",
              "amount": 240,
              "purchaseDate": "2026-05-28",
              "requestDate": "2026-06-10",
              "reason": "Arrived defective — the unit will not power on."
            },
            "daysSincePurchase": 13,
            "defectClaimed": true,
            "finalSale": false
          },
          "live": false,
          "usage": {
            "input": 477,
            "output": 20
          },
          "cached": true
        },
        {
          "stepId": "fraud_check",
          "name": "Fraud Check",
          "kind": "llm",
          "output": {
            "fraudRisk": "LOW",
            "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item not final sale, no signs of repeat abuse, identity mismatch, or impossible timeline."
          },
          "live": false,
          "usage": {
            "input": 568,
            "output": 76
          },
          "cached": true
        },
        {
          "stepId": "classify",
          "name": "Classifier",
          "kind": "llm",
          "output": {
            "category": "WITHIN_WINDOW_DEFECTIVE"
          },
          "live": false,
          "forked": true
        },
        {
          "stepId": "retrieve_policy",
          "name": "Policy Retriever",
          "kind": "rule",
          "output": {
            "policyRule": {
              "eligible": true,
              "note": "Defective within the 30-day window — full refund."
            }
          },
          "live": false
        },
        {
          "stepId": "eligibility",
          "name": "Eligibility",
          "kind": "rule",
          "output": {
            "eligible": true,
            "eligReason": "Defective within the 30-day window — full refund."
          },
          "live": false
        },
        {
          "stepId": "amount",
          "name": "Amount",
          "kind": "rule",
          "output": {
            "amount": 240
          },
          "live": false
        },
        {
          "stepId": "decision",
          "name": "Decision",
          "kind": "llm",
          "output": {
            "decision": "APPROVE",
            "rationale": "Your refund of $240 has been approved because your item was defective and reported within the 30-day return window."
          },
          "live": true,
          "usage": {
            "input": 429,
            "output": 49
          }
        }
      ],
      "finalState": {
        "claim": {
          "orderId": "A-4471",
          "customer": "Northwind Traders",
          "item": "Standard Widget (not final sale)",
          "amount": 240,
          "purchaseDate": "2026-05-28",
          "requestDate": "2026-06-10",
          "reason": "Arrived defective — the unit will not power on."
        },
        "daysSincePurchase": 13,
        "defectClaimed": true,
        "finalSale": false,
        "fraudRisk": "LOW",
        "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item not final sale, no signs of repeat abuse, identity mismatch, or impossible timeline.",
        "category": "WITHIN_WINDOW_DEFECTIVE",
        "policyRule": {
          "eligible": true,
          "note": "Defective within the 30-day window — full refund."
        },
        "eligible": true,
        "eligReason": "Defective within the 30-day window — full refund.",
        "amount": 240,
        "decision": "APPROVE",
        "rationale": "Your refund of $240 has been approved because your item was defective and reported within the 30-day return window."
      },
      "outcome": {
        "decision": "APPROVE",
        "amount": 240,
        "pass": true
      }
    }
  },
  "repair": {
    "nodeId": "classify",
    "nodeName": "Classifier",
    "originalPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- A return is valid ONLY if the request is made in the SAME CALENDAR MONTH as the purchase. If the request month differs from the purchase month, classify OUT_OF_WINDOW.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the reason is change-of-mind with no defect, classify BUYER_REMORSE.\n- Otherwise classify WITHIN_WINDOW_DEFECTIVE.",
    "patchedPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- The return window is 30 CALENDAR DAYS from the purchase date. A request is WITHIN the window if it is made 30 or fewer calendar days after the purchase date; it is OUT of the window if made more than 30 calendar days after the purchase date.\n- If the request is made more than 30 calendar days after the purchase date, classify OUT_OF_WINDOW.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the reason is change-of-mind with no defect, classify BUYER_REMORSE.\n- If the item is defective and the request is within the 30-day window (and the item is not final sale), classify WITHIN_WINDOW_DEFECTIVE.\n- Otherwise classify WITHIN_WINDOW_DEFECTIVE.",
    "rootCause": "The prompt encoded an incorrect return-window rule. It defined the window as the 'SAME CALENDAR MONTH' as the purchase date, causing it to classify any cross-month request as OUT_OF_WINDOW. The authoritative policy defines the window as 30 calendar days from the purchase date, so a 13-day-old defective claim was wrongly marked OUT_OF_WINDOW instead of WITHIN_WINDOW_DEFECTIVE.",
    "rationale": "I replaced the erroneous 'same calendar month' rule with the authoritative 30-calendar-day window measured from the purchase date, and clarified the OUT_OF_WINDOW condition to trigger only when more than 30 days have elapsed. The other categories (FINAL_SALE, BUYER_REMORSE) and the default remain unchanged, preserving the prompt's structure and JSON output contract. Under this corrected policy, a defective, non-final-sale item requested 13 days after purchase is correctly classified WITHIN_WINDOW_DEFECTIVE."
  },
  "verify": {
    "verifiedRun": {
      "id": "verify",
      "records": [
        {
          "stepId": "intake",
          "name": "Intake",
          "kind": "llm",
          "output": {
            "claim": {
              "orderId": "A-4471",
              "customer": "Northwind Traders",
              "item": "Standard Widget (not final sale)",
              "amount": 240,
              "purchaseDate": "2026-05-28",
              "requestDate": "2026-06-10",
              "reason": "Arrived defective — the unit will not power on."
            },
            "daysSincePurchase": 13,
            "defectClaimed": true,
            "finalSale": false
          },
          "live": true,
          "usage": {
            "input": 477,
            "output": 20
          }
        },
        {
          "stepId": "fraud_check",
          "name": "Fraud Check",
          "kind": "llm",
          "output": {
            "fraudRisk": "LOW",
            "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and no signals of identity mismatch, repeat abuse, or impossible timeline are present."
          },
          "live": true,
          "usage": {
            "input": 568,
            "output": 80
          }
        },
        {
          "stepId": "classify",
          "name": "Classifier",
          "kind": "llm",
          "output": {
            "category": "WITHIN_WINDOW_DEFECTIVE"
          },
          "live": true,
          "usage": {
            "input": 841,
            "output": 28
          }
        },
        {
          "stepId": "retrieve_policy",
          "name": "Policy Retriever",
          "kind": "rule",
          "output": {
            "policyRule": {
              "eligible": true,
              "note": "Defective within the 30-day window — full refund."
            }
          },
          "live": false
        },
        {
          "stepId": "eligibility",
          "name": "Eligibility",
          "kind": "rule",
          "output": {
            "eligible": true,
            "eligReason": "Defective within the 30-day window — full refund."
          },
          "live": false
        },
        {
          "stepId": "amount",
          "name": "Amount",
          "kind": "rule",
          "output": {
            "amount": 240
          },
          "live": false
        },
        {
          "stepId": "decision",
          "name": "Decision",
          "kind": "llm",
          "output": {
            "decision": "APPROVE",
            "rationale": "Your refund of $240 has been approved because the item was found defective within the 30-day return window."
          },
          "live": true,
          "usage": {
            "input": 429,
            "output": 47
          }
        }
      ],
      "finalState": {
        "claim": {
          "orderId": "A-4471",
          "customer": "Northwind Traders",
          "item": "Standard Widget (not final sale)",
          "amount": 240,
          "purchaseDate": "2026-05-28",
          "requestDate": "2026-06-10",
          "reason": "Arrived defective — the unit will not power on."
        },
        "daysSincePurchase": 13,
        "defectClaimed": true,
        "finalSale": false,
        "fraudRisk": "LOW",
        "fraudReason": "Ordinary defective-item claim within a normal 13-day timeframe, item is not final sale, and no signals of identity mismatch, repeat abuse, or impossible timeline are present.",
        "category": "WITHIN_WINDOW_DEFECTIVE",
        "policyRule": {
          "eligible": true,
          "note": "Defective within the 30-day window — full refund."
        },
        "eligible": true,
        "eligReason": "Defective within the 30-day window — full refund.",
        "amount": 240,
        "decision": "APPROVE",
        "rationale": "Your refund of $240 has been approved because the item was found defective within the 30-day return window."
      },
      "outcome": {
        "decision": "APPROVE",
        "amount": 240,
        "pass": true
      }
    },
    "eval": {
      "passed": true,
      "before": {
        "decision": "DENY",
        "amount": 0
      },
      "after": {
        "decision": "APPROVE",
        "amount": 240
      },
      "assertion": "decision===\"APPROVE\" && amount===240"
    }
  },
  "usage": {
    "input": 15830,
    "output": 2029
  }
}) as unknown as LoopResult;
