import type { Lesson, PreventionResult } from "./knowledge";

// AUTO-GENERATED by scripts/record.ts — real lessons + a real recurrence-prevention run.
export const RECORDED_LESSONS = ([
  {
    "id": "WL-001",
    "title": "Refund classifier used 'same calendar month' instead of the 30-day window",
    "failureClass": "wrong-policy-in-prompt",
    "agent": "refund-classifier",
    "culprit": "Classifier",
    "rootCause": "The prompt encoded an incorrect return-window rule. It instructed the classifier to treat a return as valid only within the SAME CALENDAR MONTH as purchase, and to mark anything in a different month as OUT_OF_WINDOW. The authoritative policy actually uses a rolling 30 CALENDAR DAYS from the purchase date. A claim made 13 days after purchase spanning a month boundary was therefore wrongly classified OUT_OF_WINDOW instead of WITHIN_WINDOW_DEFECTIVE.",
    "repairSummary": "Replace the calendar-month rule with a 30-day window.",
    "patchedPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- The return window is 30 CALENDAR DAYS from the purchase date. A request is within the window if it is made on or before the 30th calendar day after the purchase date; calendar months are irrelevant. If the request is made more than 30 calendar days after the purchase date, classify OUT_OF_WINDOW.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the reason is change-of-mind with no defect (and the item is not final sale), classify BUYER_REMORSE.\n- If the item is defective on arrival, the request is within the 30-day window, and the item is not final sale, classify WITHIN_WINDOW_DEFECTIVE (full refund).\n- Otherwise classify WITHIN_WINDOW_DEFECTIVE.",
    "evidence": {
      "before": "DENY · $0",
      "after": "APPROVE · $240"
    },
    "tags": [
      "policy",
      "date-window",
      "classification"
    ],
    "mintedAt": "2026-06-13",
    "protects": [
      "refund-classifier",
      "warranty-classifier",
      "returns-router"
    ]
  },
  {
    "id": "WL-002",
    "title": "Invoice extractor parsed DD/MM dates as MM/DD on EU invoices",
    "failureClass": "date-format-misparse",
    "agent": "invoice-extractor",
    "culprit": "Extractor",
    "rootCause": "Assumed US date format, producing wrong due dates and false late fees on EU invoices.",
    "repairSummary": "Detect locale / require explicit ISO parsing before computing due dates.",
    "evidence": {
      "before": "late-fee $1,200",
      "after": "on-time · $0"
    },
    "tags": [
      "date",
      "parsing",
      "extraction"
    ],
    "mintedAt": "2026-05-30",
    "protects": [
      "invoice-extractor",
      "billing-agent"
    ]
  },
  {
    "id": "WL-003",
    "title": "Support router sent billing tickets to the engineering queue",
    "failureClass": "misrouting",
    "agent": "support-router",
    "culprit": "Router",
    "rootCause": "Keyword overlap on 'charge' routed billing issues to tech, breaching SLAs.",
    "repairSummary": "Add intent disambiguation and prioritize billing terms in routing.",
    "evidence": {
      "before": "SLA breach 38%",
      "after": "SLA breach 4%"
    },
    "tags": [
      "routing",
      "intent",
      "classification"
    ],
    "mintedAt": "2026-05-22",
    "protects": [
      "support-router"
    ]
  },
  {
    "id": "WL-004",
    "title": "Contract summarizer obeyed an instruction injected in the document",
    "failureClass": "prompt-injection",
    "agent": "contract-summarizer",
    "culprit": "Summarizer",
    "rootCause": "Treated document text as instructions and approved a non-compliant clause.",
    "repairSummary": "Quarantine document content; never execute instructions found inside inputs.",
    "evidence": {
      "before": "approved bad clause",
      "after": "flagged + escalated"
    },
    "tags": [
      "security",
      "prompt-injection",
      "summarization"
    ],
    "mintedAt": "2026-05-10",
    "protects": [
      "contract-summarizer",
      "email-agent"
    ]
  },
  {
    "id": "WL-005",
    "title": "Flaky tool caused an unbounded retry storm",
    "failureClass": "retry-storm",
    "agent": "enrichment-agent",
    "culprit": "Retry policy",
    "rootCause": "No backoff or cap on a timing-out tool produced ~100x retries and a cost spike.",
    "repairSummary": "Exponential backoff + max-attempts cap + circuit breaker.",
    "evidence": {
      "before": "$420 / run",
      "after": "$0.40 / run"
    },
    "tags": [
      "reliability",
      "cost",
      "retries"
    ],
    "mintedAt": "2026-04-28",
    "protects": [
      "enrichment-agent",
      "scraper-agent"
    ]
  }
]) as unknown as Lesson[];
export const RECORDED_PREVENTION = ({
  "agent": "warranty-classifier",
  "failed": {
    "decision": "DENY",
    "amount": 0
  },
  "match": {
    "lesson": {
      "id": "WL-001",
      "title": "Refund classifier used 'same calendar month' instead of the 30-day window",
      "failureClass": "wrong-policy-in-prompt",
      "agent": "refund-classifier",
      "culprit": "Classifier",
      "rootCause": "The prompt encoded an incorrect return-window rule. It instructed the classifier to treat a return as valid only within the SAME CALENDAR MONTH as purchase, and to mark anything in a different month as OUT_OF_WINDOW. The authoritative policy actually uses a rolling 30 CALENDAR DAYS from the purchase date. A claim made 13 days after purchase spanning a month boundary was therefore wrongly classified OUT_OF_WINDOW instead of WITHIN_WINDOW_DEFECTIVE.",
      "repairSummary": "Replace the calendar-month rule with a 30-day window.",
      "patchedPrompt": "You classify a refund claim into exactly one category.\nCategories: WITHIN_WINDOW_DEFECTIVE, OUT_OF_WINDOW, FINAL_SALE, BUYER_REMORSE.\n\nReturn-window policy (apply literally):\n- The return window is 30 CALENDAR DAYS from the purchase date. A request is within the window if it is made on or before the 30th calendar day after the purchase date; calendar months are irrelevant. If the request is made more than 30 calendar days after the purchase date, classify OUT_OF_WINDOW.\n- If the item is marked final sale, classify FINAL_SALE.\n- If the reason is change-of-mind with no defect (and the item is not final sale), classify BUYER_REMORSE.\n- If the item is defective on arrival, the request is within the 30-day window, and the item is not final sale, classify WITHIN_WINDOW_DEFECTIVE (full refund).\n- Otherwise classify WITHIN_WINDOW_DEFECTIVE.",
      "evidence": {
        "before": "DENY · $0",
        "after": "APPROVE · $240"
      },
      "tags": [
        "policy",
        "date-window",
        "classification"
      ],
      "mintedAt": "2026-06-13",
      "protects": [
        "refund-classifier",
        "warranty-classifier",
        "returns-router"
      ]
    },
    "confidence": 0.72,
    "rationale": "The warranty classifier wrongly labeled a 13-day-old purchase as OUT_OF_WINDOW, which mirrors WL-001's mechanism: a policy/date-window misapplication in the classification prompt. The underlying failure is the classifier using an incorrect date-window rule, not a date parsing/format error (WL-002). Confidence is moderate since the specific policy text isn't confirmed, but the mechanism (wrong window logic causing misclassification) aligns."
  },
  "prevented": {
    "decision": "APPROVE",
    "amount": 520,
    "pass": true
  },
  "usage": {
    "input": 5529,
    "output": 536
  }
}) as unknown as PreventionResult;
