// Capture ONE real WorldLine loop (live Opus 4.8) into a TS module the app can
// load instantly as a reliable demo default. Re-run live is still available.
//   set -a; . ./.env; set +a; npx tsx scripts/record.ts
import { writeFileSync } from "node:fs";
import { runFullLoop } from "../lib/worldline/loop";
import { mintLesson, runPrevention, SEED_LESSONS } from "../lib/worldline/knowledge";

(async () => {
  const r = await runFullLoop();
  if (!r.verify.eval.passed || r.bisect.culpritId !== "classify") {
    console.error("Refusing to record a non-golden run:", r.bisect.culpritId, r.verify.eval.passed);
    process.exit(1);
  }
  const body =
    `import type { LoopResult } from "./types";\n\n` +
    `// AUTO-GENERATED by scripts/record.ts — a REAL captured WorldLine run (live Opus 4.8).\n` +
    `// Used as the instant, reliable demo default; "Re-run live" recomputes via /api/loop.\n` +
    `export const RECORDED = (${JSON.stringify(r, null, 2)}) as unknown as LoopResult;\n`;
  writeFileSync("lib/worldline/recorded.ts", body);
  console.log(`recorded ✓  culprit=${r.bisect.culpritId} passed=${r.verify.eval.passed} tokens(in/out)=${r.usage.input}/${r.usage.output}`);

  // institutional memory: mint a lesson from this run, accumulate, capture a prevention
  const minted = mintLesson(r);
  const lessons = [minted, ...SEED_LESSONS.filter((l) => l.id !== minted.id)];
  const prevention = await runPrevention(lessons);
  const memBody =
    `import type { Lesson, PreventionResult } from "./knowledge";\n\n` +
    `// AUTO-GENERATED by scripts/record.ts — real lessons + a real recurrence-prevention run.\n` +
    `export const RECORDED_LESSONS = (${JSON.stringify(lessons, null, 2)}) as unknown as Lesson[];\n` +
    `export const RECORDED_PREVENTION = (${JSON.stringify(prevention, null, 2)}) as unknown as PreventionResult;\n`;
  writeFileSync("lib/worldline/recorded-memory.ts", memBody);
  console.log(`recorded-memory ✓  match=${prevention.match.lesson?.id} prevented=${prevention.prevented?.pass}`);
})().catch((e) => {
  console.error("record failed:", e);
  process.exit(1);
});
