// Capture ONE real WorldLine loop (live Opus 4.8) into a TS module the app can
// load instantly as a reliable demo default. Re-run live is still available.
//   set -a; . ./.env; set +a; npx tsx scripts/record.ts
import { writeFileSync } from "node:fs";
import { runFullLoop } from "../lib/worldline/loop";

(async () => {
  const r = await runFullLoop();
  if (!r.verify.eval.passed || r.bisect.culpritId !== "classify") {
    console.error("Refusing to record a non-golden run:", r.bisect.culpritId, r.verify.eval.passed);
    process.exit(1);
  }
  const body =
    `import type { LoopResult } from "./types";\n\n` +
    `// AUTO-GENERATED by scripts/record.ts — a REAL captured WorldLine run (live Opus 4.8).\n` +
    `// Used as the instant, reliable demo default; "Re-run live" recomputes via /api/loop.\n` +
    `export const RECORDED = (${JSON.stringify(r, null, 2)}) as unknown as LoopResult;\n`;
  writeFileSync("lib/worldline/recorded.ts", body);
  console.log(`recorded ✓  culprit=${r.bisect.culpritId} passed=${r.verify.eval.passed} tokens(in/out)=${r.usage.input}/${r.usage.output}`);
})().catch((e) => {
  console.error("record failed:", e);
  process.exit(1);
});
